# Generated by Django 2.2 on 2019-06-18 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_on',
        ),
        migrations.AddField(
            model_name='job',
            name='date_applied',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='date_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='date_job_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.CharField(default=datetime.date(2019, 6, 18), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('A', 'Apply'), ('I', 'Interview'), ('F', 'Follow Up'), ('O', 'Outcomes')], default='A', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Job')),
            ],
        ),
    ]
