# Generated by Django 2.2 on 2019-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190618_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('A', 'Apply'), ('I', 'Interview'), ('F', 'Follow Up'), ('O', 'Outcomes')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
