# Generated by Django 2.2 on 2019-06-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_job_prioritized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_company', models.BooleanField(default=False)),
                ('research_position', models.BooleanField(default=False)),
                ('contact_connection', models.BooleanField(default=False)),
                ('customize_resume', models.BooleanField(default=False)),
                ('customize_portfolio', models.BooleanField(default=False)),
                ('customize_cover_letter', models.BooleanField(default=False)),
                ('review_documents', models.BooleanField(default=False)),
                ('email_checkin', models.BooleanField(default=False)),
                ('research_job_interviewer', models.BooleanField(default=False)),
                ('research_job_reqs', models.BooleanField(default=False)),
                ('research_salary', models.BooleanField(default=False)),
                ('practice_interview_questions', models.BooleanField(default=False)),
                ('send_thanks', models.BooleanField(default=False)),
                ('schedule_followup', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Job')),
            ],
        ),
    ]
