# Generated by Django 2.2 on 2019-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190619_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prioritized',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=1),
        ),
    ]
