# Generated by Django 2.2 on 2019-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190619_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prioritized',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='False', max_length=1),
        ),
    ]
