# Generated by Django 2.2 on 2019-06-21 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190620_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_job_posted',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
