# Generated by Django 2.2 on 2019-06-21 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190620_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_job_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
