# Generated by Django 2.2 on 2019-06-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190620_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('A', 'Apply'), ('I', 'Interview'), ('F', 'Follow Up'), ('O', 'Outcomes')], default='A', max_length=10),
        ),
    ]
