# Generated by Django 2.2 on 2019-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190620_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prioritized',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='types',
            field=models.CharField(choices=[('I', 'Internship'), ('C', 'Contract'), ('P', 'Part-Time'), ('F', 'Full-Time')], default='I', max_length=1),
        ),
    ]
