# Generated by Django 2.2 on 2019-06-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190620_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prioritized',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1),
        ),
    ]
